# Generated by Django 5.2.1 on 2025-07-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scissors', '0002_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
