# Generated by Django 5.2.1 on 2025-07-22 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scissors', '0003_posts_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='datetimeslots',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scissors.staff'),
        ),
    ]
