# Generated by Django 5.2.1 on 2025-06-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scissors', '0003_alter_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimeSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('free', 'Free'), ('onhold', 'On Hold'), ('booked', 'Booked')], default='free', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'datetime_slots',
            },
        ),
    ]
