# Generated by Django 5.2.1 on 2025-06-18 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scissors', '0004_datetimeslots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='date_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scissors.datetimeslots'),
        ),
    ]
