# Generated by Django 5.2.1 on 2025-07-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scissors', '0004_datetimeslots_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='datetimeslots',
            name='appointment_status',
            field=models.CharField(choices=[('open', 'Open'), ('new', 'New Appointment'), ('in_progress', 'In Progress'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='open', max_length=50),
        ),
    ]
